name: movie_discovery
description: "Movie Discovery App — Platform Commons Engineering Assignment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.7

  # Networking
  dio: ^5.7.0

  # Local Database
  drift: ^2.20.3
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24

  # Background Sync
  workmanager: ^0.5.2

  # Connectivity
  connectivity_plus: ^6.1.4

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^9.2.2

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  drift_dev: ^2.20.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/svg/
    - assets/fonts/
